#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.5 on Wed May 21 15:46:18 2025
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Ventana(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Ventana.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((585, 500))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)

        self.notebook = wx.Notebook(self.panel_1, wx.ID_ANY, style=wx.NB_BOTTOM)
        sizer_1.Add(self.notebook, 1, wx.ALL | wx.EXPAND, 0)

        self.notebook_Page1 = wx.Panel(self.notebook, wx.ID_ANY)
        self.notebook.AddPage(self.notebook_Page1, "Page 1")

        sizer_izqd_pag1 = wx.BoxSizer(wx.VERTICAL)

        sizer_opc_jueg = wx.StaticBoxSizer(wx.StaticBox(self.notebook_Page1, wx.ID_ANY, "Opciones del juego"), wx.VERTICAL)
        sizer_izqd_pag1.Add(sizer_opc_jueg, 2, wx.EXPAND, 0)

        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_opc_jueg.Add(sizer_5, 1, wx.ALL | wx.EXPAND, 0)

        label_1 = wx.StaticText(self.notebook_Page1, wx.ID_ANY, u"Nº Jugadores", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_5.Add(label_1, 0, wx.ALL | wx.EXPAND, 3)

        self.spin_ctrl_5 = wx.SpinCtrl(self.notebook_Page1, wx.ID_ANY, "0", min=0, max=100)
        sizer_5.Add(self.spin_ctrl_5, 0, 0, 0)

        sizer_6 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_opc_jueg.Add(sizer_6, 1, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.notebook_Page1, wx.ID_ANY, u" Nº Columnas", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_6.Add(label_2, 0, wx.ALL | wx.EXPAND, 1)

        self.spin_ctrl_2 = wx.SpinCtrl(self.notebook_Page1, wx.ID_ANY, "0", min=0, max=100)
        sizer_6.Add(self.spin_ctrl_2, 0, wx.ALL, 0)

        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_opc_jueg.Add(sizer_7, 1, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.notebook_Page1, wx.ID_ANY, u"   Nº Fichas", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_7.Add(label_3, 0, wx.ALL | wx.EXPAND, 6)

        self.spin_ctrl_3 = wx.SpinCtrl(self.notebook_Page1, wx.ID_ANY, "0", min=0, max=100)
        sizer_7.Add(self.spin_ctrl_3, 0, wx.ALL | wx.EXPAND, 4)

        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_opc_jueg.Add(sizer_8, 1, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.notebook_Page1, wx.ID_ANY, u"      Nº Dados", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_8.Add(label_4, 0, wx.ALL | wx.EXPAND, 2)

        self.spin_ctrl_4 = wx.SpinCtrl(self.notebook_Page1, wx.ID_ANY, "0", min=0, max=100)
        sizer_8.Add(self.spin_ctrl_4, 0, wx.ALL, 5)

        sizer_opc_juga = wx.StaticBoxSizer(wx.StaticBox(self.notebook_Page1, wx.ID_ANY, "Opciones de los jugadores"), wx.VERTICAL)
        sizer_izqd_pag1.Add(sizer_opc_juga, 3, wx.ALL | wx.EXPAND, 0)

        self.list_box_2 = wx.ListBox(self.notebook_Page1, wx.ID_ANY, choices=["choice 1"])
        sizer_opc_juga.Add(self.list_box_2, 1, wx.ALL | wx.EXPAND, 0)

        sizer_nombre = wx.BoxSizer(wx.HORIZONTAL)
        sizer_izqd_pag1.Add(sizer_nombre, 1, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.notebook_Page1, wx.ID_ANY, "Nombre", style=wx.ALIGN_CENTER_HORIZONTAL | wx.ST_ELLIPSIZE_START)
        sizer_nombre.Add(label_5, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 0)

        self.text_ctrl_1 = wx.TextCtrl(self.notebook_Page1, wx.ID_ANY, "")
        sizer_nombre.Add(self.text_ctrl_1, 1, wx.ALL | wx.EXPAND, 0)

        sizer_imagen = wx.BoxSizer(wx.HORIZONTAL)
        sizer_izqd_pag1.Add(sizer_imagen, 3, wx.ALL | wx.EXPAND, 3)

        label_6 = wx.StaticText(self.notebook_Page1, wx.ID_ANY, "Imagen", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_imagen.Add(label_6, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 0)

        self.combo_box_1 = wx.ComboBox(self.notebook_Page1, wx.ID_ANY, choices=["ss", "", "", "", ""], style=wx.CB_DROPDOWN)
        sizer_imagen.Add(self.combo_box_1, 1, wx.ALL | wx.EXPAND, 0)

        sizer_tipo = wx.BoxSizer(wx.HORIZONTAL)
        sizer_izqd_pag1.Add(sizer_tipo, 1, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.notebook_Page1, wx.ID_ANY, "Tipo", style=wx.ALIGN_CENTER_HORIZONTAL)
        sizer_tipo.Add(label_7, 1, wx.ALIGN_CENTER_VERTICAL | wx.ALL, 0)

        self.radio_box_1 = wx.RadioBox(self.notebook_Page1, wx.ID_ANY, "", choices=["Humano", "Maquina Tonta", "Maquina Lista"], majorDimension=1, style=wx.RA_SPECIFY_COLS)
        self.radio_box_1.SetSelection(0)
        sizer_tipo.Add(self.radio_box_1, 2, wx.ALL | wx.EXPAND, 0)

        self.button_1 = wx.Button(self.notebook_Page1, wx.ID_ANY, "JUGAR !")
        self.button_1.SetFont(wx.Font(10, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        self.button_1.SetBitmap(wx.Bitmap("C:\\Users\\34630\\Desktop\\PYTHON\\Pargammon\\practica2\\playing_cards.png", wx.BITMAP_TYPE_ANY))
        sizer_izqd_pag1.Add(self.button_1, 1, wx.ALL | wx.EXPAND, 1)

        self.notebook_Page2 = wx.Panel(self.notebook, wx.ID_ANY)
        self.notebook.AddPage(self.notebook_Page2, "Page 2")

        sizer_11 = wx.BoxSizer(wx.VERTICAL)

        sizer_12 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_Page2, wx.ID_ANY, "Historial de Jugadas"), wx.VERTICAL)
        sizer_11.Add(sizer_12, 2, wx.EXPAND, 0)

        self.list_box_3 = wx.ListBox(self.notebook_Page2, wx.ID_ANY, choices=["choice 1"])
        sizer_12.Add(self.list_box_3, 1, wx.ALL | wx.EXPAND, 0)

        sizer_13 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_Page2, wx.ID_ANY, "Turno y Puntuacion"), wx.VERTICAL)
        sizer_11.Add(sizer_13, 1, wx.EXPAND, 0)

        self.list_ctrl_1 = wx.ListCtrl(self.notebook_Page2, wx.ID_ANY, style=wx.LC_HRULES | wx.LC_REPORT | wx.LC_VRULES)
        self.list_ctrl_1.AppendColumn("A", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.list_ctrl_1.AppendColumn("B", format=wx.LIST_FORMAT_LEFT, width=-1)
        self.list_ctrl_1.AppendColumn("C", format=wx.LIST_FORMAT_LEFT, width=-1)
        sizer_13.Add(self.list_ctrl_1, 1, wx.ALL | wx.EXPAND, 0)

        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_Page2, wx.ID_ANY, "Partidas Jugadas"), wx.HORIZONTAL)
        sizer_11.Add(sizer_2, 1, wx.EXPAND, 0)

        self.label_8 = wx.StaticText(self.notebook_Page2, wx.ID_ANY, "Partida 1", style=wx.ALIGN_CENTER_HORIZONTAL)
        self.label_8.SetFont(wx.Font(15, wx.FONTFAMILY_ROMAN, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_2.Add(self.label_8, 1, wx.ALL | wx.EXPAND, 0)

        sizer_14 = wx.StaticBoxSizer(wx.StaticBox(self.notebook_Page2, wx.ID_ANY, "Dados"), wx.HORIZONTAL)
        sizer_11.Add(sizer_14, 1, wx.EXPAND, 0)

        bitmap_1 = wx.StaticBitmap(self.notebook_Page2, wx.ID_ANY, wx.Bitmap("./dado1.png", wx.BITMAP_TYPE_ANY))
        sizer_14.Add(bitmap_1, 0, 0, 0)

        sizer_14.Add((0, 0), 0, 0, 0)

        sizer_14.Add((0, 0), 0, 0, 0)

        sizer_14.Add((0, 0), 0, 0, 0)

        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11.Add(sizer_15, 1, wx.ALL | wx.EXPAND, 1)

        self.button_2 = wx.Button(self.notebook_Page2, wx.ID_ANY, "Saltar Dado")
        self.button_2.SetFont(wx.Font(8, wx.FONTFAMILY_DECORATIVE, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        self.button_2.SetBitmap(wx.Bitmap("C:\\Users\\34630\\Desktop\\PYTHON\\Pargammon\\practica2\\dado_skip.png", wx.BITMAP_TYPE_ANY))
        sizer_15.Add(self.button_2, 0, wx.ALL | wx.EXPAND, 0)

        self.button_3 = wx.Button(self.notebook_Page2, wx.ID_ANY, "Finalizar Partida")
        self.button_3.SetFont(wx.Font(8, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        self.button_3.SetBitmap(wx.Bitmap("C:\\Users\\34630\\Desktop\\PYTHON\\Pargammon\\practica2\\stop.png", wx.BITMAP_TYPE_ANY))
        sizer_15.Add(self.button_3, 0, wx.ALL | wx.EXPAND, 0)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        sizer_1.Add(self.panel_2, 1, wx.EXPAND, 0)

        self.notebook_Page2.SetSizer(sizer_11)

        self.notebook_Page1.SetSizer(sizer_izqd_pag1)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        self.Bind(wx.EVT_BUTTON,self.cambiar,self.button_2)
        
    def cambiar(self,event):
        self.label_8.SetLabel(f"Partida{2}")
        # end wxGlade

# end of class Ventana

class MyApp(wx.App):
    def OnInit(self):
        self.frame = Ventana(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
